[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "nest eyebrow original syrup valid awful pause year grab reduce find outside betray custom library attack accuse oxygen umbrella movie tunnel frown escape second"
